development:
  clients:
    default:
      database: bookshelfweb_development
      hosts:
        - localhost:27017
      options:
      server_selection_timeout: 1
  options:
    raise_not_found_error: true

test:
  clients:
    default:
      database: bookshelfweb_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
